# SPDX-FileCopyrightText: 2023 Number6174
# SPDX-License-Identifier: CC0-1.0

version: 2
updates:
  - package-ecosystem: "pip" 
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
