# SPDX-FileCopyrightText: 2021 Number6174
# SPDX-License-Identifier: CC0-1.0

name: py2exe

on:
  push:
    tags:
    - '[0-1]+.[0-1]+.[0-9]+'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: py2exe freeze
      run: |
        python setup.py py2exe
    - name: Zip Files
      run: |
        7z a -tzip WritingHTTPServer.zip ./dist/*
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: WritingHTTPServer.zip
