# SPDX-FileCopyrightText: 2021 Number6174
# SPDX-License-Identifier: CC0-1.0

name: pyinstaller

on:
  push:
    tags:
    - '[0-1]+.[0-1]+.[0-9]+'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version-file: '.python-version'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: pyinstaller freeze
      run: |
        pyinstaller server.psec
    - name: Zip Files
      run: |
        7z a -tzip WritingHTTPServer.zip ./dist/server/*
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: WritingHTTPServer.zip
